fintoc/resources.py

This pull request should close #1.

Add a check to transaction date value before isoparsing

---

fintoc/resources.py

Add recipient and sender information to a transfer movement

---

poetry.lock
pyproject.toml

This Pull Request is just an upgrade of the `httpx` dependency. I tested some functions with the new version and everything seemed to be working OK. This is expected, however, as the library itself is barely being used, so changes shouldn't affect how `fintoc-python` works.
None.

Upgrade httpx dependency

---

pyproject.toml

Prepare 1.1.0 release

---

scripts/bump.sh

Adjust release commit message of the bump script to fit the rest of the commits
None.
None.

Update the bump script

---

pyproject.toml

Bump up version to `2.0.0` (breaking changes on PR #20)

Prepare 2.0.0 release

---

tests/test_utils.py

I delete a repeated test. It was on `tests/test_utils.py`, in `TestGetResourceClass`, and it was testing the same as `test_int_resource` method
None.
None.

test(utils): delete repetead test

---

fintoc/version.py
pyproject.toml

Prepare 2.1.2 release

---

fintoc/version.py
pyproject.toml

Prepare 2.2.0 release

---

fintoc/version.py
pyproject.toml

Prepare 2.2.1 release

---

fintoc/version.py
pyproject.toml

Prepare 2.2.2 release

---

.github/workflows/linters.yml
.github/workflows/release.yml
.github/workflows/tests.yml
Makefile
codecov.yml
poetry.lock
pyproject.toml

The CI/CD workflow got broken. This PR fixes it.
None.
Change the `get-poetry` command from the `Makefile` to use the latest method from the Python Poetry documentation.

Fix ci/cd workflow

---

README.md
fintoc/core.py
fintoc/managers/__init__.py
fintoc/managers/charges_manager.py
fintoc/managers/subscription_intents_manager.py
fintoc/resources/__init__.py
fintoc/resources/charge.py
fintoc/resources/subscription_intent.py

This Pull Request adds support for the Direct Debit product to the SDK. It adds SubscriptionIntent and Charges objects and the Managers. It also documents the new functionality.
None.
None.

Direct debit

---

fintoc/version.py
pyproject.toml

Prepare 2.3.0 release

---

fintoc/version.py
pyproject.toml

Se pasa el cambio de minor version que contiene [estos](https://github.com/fintoc-com/fintoc-python/pull/58) cambios

pre-release: prepare 2.4.0 release

---

.github/workflows/tests.yml

El uploader del coverage está teniendo algunas issues, por lo que lo eliminaremos por mientras para que no bloquee los deploy

fix(ci): remove upload coverage

---

fintoc/version.py
pyproject.toml

Prepare 2.5.0 release with the following changes: #65 #66 #67 #68 #69 #70 #71 #72 
None.
None.

pre-release: prepare 2.5.0 release

---

fintoc/core.py
fintoc/managers/v2/__init__.py
fintoc/managers/v2/entities_manager.py
fintoc/resources/__init__.py
fintoc/resources/v2/__init__.py
fintoc/resources/v2/entity.py
tests/test_integration.py

Add support for v2/entities endpoints.
```python
from fintoc import Fintoc
client = Fintoc("your_api_key")
entities = client.v2.entities.list()
for e in entities:
print(e.serialize())
entity = client.v2.entities.get('some_entity_id')
print(entity.serialize())
``` 
None.
None.

feature(entities): add entities resource

---

fintoc/core.py
fintoc/managers/v2/__init__.py
fintoc/managers/v2/account_verifications_manager.py
fintoc/resources/__init__.py
fintoc/resources/v2/__init__.py
fintoc/resources/v2/account_verification.py
tests/test_integration.py

In the context of the transfers product, a new endpoint is required to validate accounts by making a microtransfer to the account being validated, in order to obtain the CEP (Electronic Payment Certificate) and deliver this information to the merchant.
This PR includes the integration to use the account verification resources.
None.
None.

[PLT-3052] Feat/account verifications

---

fintoc/client.py
fintoc/paginator.py
fintoc/version.py
pyproject.toml
tests/conftest.py
tests/test_client.py
tests/test_integration.py
tests/test_paginator.py

- Add Account Verification resource API
[None]
[None]

Release 2.7.0

---

fintoc/version.py
pyproject.toml

Bump version to 2.8.0 for release

pre-release: prepare 2.8.0 release

---

fintoc/version.py
pyproject.toml

- Add return method to transfer API
[None]
[None]

pre-release: prepare 2.9.0 release

---

fintoc/version.py
pyproject.toml

- Added expire functionality to payment intents (cash payments only)
[None]
[None]

pre-release: prepare 2.10.0 release

---

fintoc/managers/v2/__init__.py
fintoc/managers/v2/accounts_manager.py
fintoc/managers/v2/movements_manager.py
fintoc/resources/v2/__init__.py
fintoc/resources/v2/movement.py
fintoc/version.py
pyproject.toml
tests/test_integration.py

- Add Movements v2 manager
[None]
[None]

Release 2.11.0

---

fintoc/version.py
pyproject.toml

Prepare 2.12.0 release with version bump.
None.
None.

pre-release: prepare 2.12.0 release
